version: '3.3'
services:
  urlsortener-01:
    container_name: urlsortener-01
    build:
      context: ./
      dockerfile: app.Dockerfile
    environment:
      - GRIDDB_HOST=griddb01
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    ports:
      - 8080:8080
    depends_on:
      - griddb01
  griddb01:
    container_name: griddb01
    build:
      context: ./dockergriddb
      dockerfile: Dockerfile
    ports:
      - 10001:10001
    volumes:
      - "volgriddb:/var/lib/gridstore"

volumes:
  volgriddb: